# Generated by Django 3.0.5 on 2020-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselelement',
            name='subscription',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carouselelement',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='carouselelement',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
