# Generated by Django 3.0.5 on 2020-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20200416_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselelement',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='carouselelement',
            name='subscription',
            field=models.TextField(max_length=300),
        ),
    ]
