# Generated by Django 3.0.5 on 2020-04-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_remove_order_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
