# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import welcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=welcome.models.image_folder),
        ),
    ]
