# Generated by Django 3.0.5 on 2020-04-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_remove_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buying_type',
        ),
    ]
