# Generated by Django 3.0.5 on 2020-04-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20200416_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselelement',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carouselelement',
            name='subscription',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
