# Generated by Django 3.0.5 on 2020-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20200416_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselelement',
            name='button',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='carouselelement',
            name='link',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
