# Generated by Django 3.0.5 on 2020-04-20 17:01

from django.db import migrations, models
import welcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_auto_20200416_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselelement',
            name='image',
            field=models.ImageField(blank=True, upload_to=welcome.models.image_folder),
        ),
    ]
