# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_middlwarenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='middlwarenotification',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
