# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0026_auto_20190416_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='middlwarenotification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='middlwarenotification',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='MiddlwareNotification',
        ),
    ]
