# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import welcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0029_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=welcome.models.image_folder)),
            ],
        ),
    ]
