# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0030_carouselelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselelement',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
