# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0032_part_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselelement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carouselelement',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят в обработку', 'Принят в обработку'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Оплачен, выполняется', 'Оплачен, выполняется'), ('Ожидает получения', 'Ожидает получения'), ('Выполнен', 'Выполнен')], default='Принят в обработку', max_length=100),
        ),
    ]
