# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-06 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0033_auto_20200406_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
