# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-06 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import welcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0036_auto_20200406_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(upload_to=welcome.models.image_folder)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.Part')),
            ],
        ),
    ]
