# Generated by Django 3.0.5 on 2020-04-07 11:55

from django.db import migrations, models
import welcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0039_auto_20200406_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(default='', upload_to=welcome.models.image_folder),
        ),
    ]
